pipeline {
    agent any
    
    tools {
        nodejs 'nodejs_20'
    }

    environment {
        NGINX_PORT = 80
        NGINX_CONF_PATH = "/etc/nginx/sites-available/"
    }

    stages {
        stage('Clone') {
            steps {
                script {
                    echo "Cloning repository from ${GITHUB_URL}"
                    git url: "${GITHUB_URL}", branch: 'main'
                }
            }
        }
        
        stage('Load Environment Variables') {
            steps {
                dir("${REPO_NAME}") {
                    script {
                        echo "Loading environment variables from .env file"
                        sh '''
                            set -a
                            source .env
                            for var in $(cat .env | cut -d= -f1); do
                                echo "Setting environment variable $var"
                                export "$var=${!var}"
                            done
                            set +a
                        '''
                    }
                }
            }
        }

        stage('Check soft versions') {
            steps {
                script {
                    sh 'node --version'
                    sh 'npm --version'
                }
            }
        }
        
        stage('Install Dependencies') {
            steps {
                script {
                    sh 'rm -rf node_modules/'
                    sh 'npm install'
                }
            }
        }

        stage('Change NGINX Config') {
            steps {
                script {
                    sh """
                        # Utwórz plik, jeśli nie istnieje
                        touch ${NGINX_CONF_PATH}/${REPO_NAME}
                        chmod 666 ${NGINX_CONF_PATH}

                        # Zapisz konfigurację do pliku
                        echo 'server {
                            listen ${NGINX_PORT};
                            server_name localhost;

                            location / {
                                proxy_pass http://localhost:${SERV_PORT};
                                proxy_http_version 1.1;
                                proxy_set_header Upgrade \$http_upgrade;
                                proxy_set_header Connection 'upgrade';
                                proxy_set_header Host \$host;
                                proxy_cache_bypass \$http_upgrade;
                            }
                        }' | tee ${NGINX_CONF_PATH}/${REPO_NAME}
                    """

                    sh """
                        if [ ! -f /etc/nginx/sites-enabled/${REPO_NAME}.conf ]; then
                            ln -s ${NGINX_CONF_PATH}/${REPO_NAME} /etc/nginx/sites-enabled/${REPO_NAME}.conf
                        fi
                    """
                    
                    sh 'docker restart nginx'
                }
            }
        }

        stage('Run Project') {
            steps {
                script {
                    sh 'node server.js'
                }
            }
        }
    }
}